- name: ESLint checker
  # You may pin to the exact commit or the version.
  # uses: ninosaurus/eslint-check@30ce7263e3f4b0bebc3cc06897bdf4ab8524a424
  uses: ninosaurus/eslint-check@v5.3.1
  with:
    # github security token
    repo-token: 
    # relative directory to node_modules
    custom-directory: 
    # relative path to eslint config file eg. .eslintrc
    eslint-config-path: 
